### PR TITLE
Updates and improvements

### PR DESCRIPTION
**Pull request by AlexOConnorHub**
I updated this a bit :) This should take care of #1

### CODE REVIEW

**Comment by Digimoney19** [comment]
Mind giving us a video tutorial on how to use it ? Just for the noobs between us, please.

**Comment by AlexOConnorHub** [comment]
Videos don't usually link well on Github, but I did update the README though. There is now a `config.json` file to put the e-mail address into. That allows for each script to get the target e-mail from one location. All of the required modules are now placed into a file named `requirements.txt`. This allows everything to be installed with one command `pip install -r requirements.txt`. From there, you just run the scripts (`python file.py`).

**Comment by retropele** [comment]
Can I ask about implementing this on Linux? :)

**Comment by AlexOConnorHub** [comment]
@retropele You should run `pip install -r requirements.txt` and all of the python dependencies should be installed *provided that you already installed Python.

For setting up Selenium, you should consult a source that has information relevant to the specific flavor of Linux that you are using. (For instance, if you're using Arch, consult the Arch wiki ect.)

**Comment by ennouri0maak** [comment]
thanks Alex for rectifying the project

**Pull request closed without merging**
